---
- name: View before hostname
  ansible.builtin.debug:
    var: ansible_facts['hostname']

- name: Host Name Settings
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Get hostname
  ansible.builtin.setup:
    filter:
      - "ansible_hostname"
  register: result_hostname

- name: View affter hostname
  ansible.builtin.debug:
    var: result_hostname.ansible_facts.ansible_hostname

- name: Check hostname
  ansible.builtin.assert:
    that:
      - result_hostname.ansible_facts.ansible_hostname == inventory_hostname
    fail_msg: "Host name is not as expected"
